name: My Name

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Check out the code from the repository
      - name: The name of the first step
        run: echo "The text from the first step"
      
      - name: The name of the second step
        run: |
          echo "List files"
          ls -l
          cat src/math_operations.py   

    


