name: My Name

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y
      
      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      
      - name: Upload the dragon.file to be used in the next jobs
        uses: actions/upload-artifact@v4
        with:
          name: dragon-fly
          path: dragon.txt
      

  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Download dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon-fly
      - name: If The file dragon.txt exist
        run: grep -i "dragon" dragon.txt
    

  third_job:
    runs-on: ubuntu-latest
    needs: second_job
    
    steps:
      - name: Printing the dragon.txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-fly
      - name: Print the file
        run: cat dragon.txt
      - name: Deploy the file
        run: echo "deploying.....!!!"
     

    


