name: My Name

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: The name of the first step
        run: echo "The text from the first step"
      
      - name: The name of the second step
        run: |
          echo "List files"
          ls -l
      - name: The third step
        run: cat math_operations.py      

    


