name: My Name

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Check out the code from the repository
      - name: Execution with shell script
        run: |
          chmod +x shell-script.sh
          ./shell-script.sh

      
      - name: List the Repository files
        run:  ls -ltra

    


